resolver: lts-6.6
packages:
- '.'
- location:
    git:  https://github.com/agocorona/transient.git
    commit: 3b4fc693c2b573a6dd77c261a1d59214b2b54a81

  extra-dep: true
extra-package-dbs: []
flags: {}

