resolver: lts-6.6
packages:
- '.'
- location:
    git: https://github.com/agocorona/transient.git
    commit: d9ee775d84b4d9aa7c4df3fa441450b8640a0d63
  extra-dep: true
extra-package-dbs: []
flags: {}
