resolver: lts-6.6
packages:
- '.'
- location:
    git: https://github.com/agocorona/transient.git
    commit: 7c779900399c1ed302e8b5199dea491822536bc1
  extra-dep: true
extra-package-dbs: []
flags: {}

