resolver: lts-6.6
packages:
- '.'
- location:
    git: https://github.com/agocorona/transient.git
    commit: 5d67ec5b47166110abc7d1a3e1d3618aa5b3f25e
  extra-dep: true
extra-package-dbs: []
flags: {}
