resolver: lts-6.6
packages:
- '.'
- location:
    git: https://github.com/agocorona/transient.git
    commit: 8573c0b7d77197af94e5d46c60b3d361f0b4dfae
  extra-dep: true
extra-package-dbs: []
flags: {}
