resolver: lts-7.7
packages:
- '.'
- location:
    git: https://github.com/transient-haskell/transient.git
    commit: 1864f1f4e3a3ba472f471b3e4743d19d7362bebc
  extra-dep: true
extra-package-dbs: []
flags: {}
