resolver: lts-6.6
packages:
- '.'
- location:
    git: https://github.com/agocorona/transient.git
    commit: fb8b53c02fd8b768fc1a877b76b87817e1e971e3
  extra-dep: true
extra-package-dbs: []
flags: {}

