resolver: lts-6.6
packages:
- '.'
- location:
    git: https://github.com/agocorona/transient.git
    commit: 53f8d775055934c87fdf0f56602c17369b0d8233
  extra-dep: true
extra-package-dbs: []
flags: {}
