resolver: lts-6.6
packages:
- '.'
- location:
    git:  https://github.com/agocorona/transient.git
    commit: cc8fdd406e3547f8bb316cecdded2776afb6062c
  extra-dep: true
extra-package-dbs: []
flags: {}

