resolver: lts-6.6
packages:
- '.'
- location:
    git:  https://github.com/agocorona/transient.git
    commit: 44062d3c8b29c9d357e07f6f023c4345ba0d71b8
  extra-dep: true
extra-package-dbs: []
flags: {}

