resolver: lts-6.6
packages:
- '.'
- location:
    git: https://github.com/agocorona/transient.git
    commit: 8d44c8fee7ad10e76385dc68898af09c55819846
  extra-dep: true
extra-package-dbs: []
flags: {}
